questions = ["Name the currency used in Japan:\na.Taka b.Dinar c.Ngultrum d.Yen",
             "Which colors must be mixed together to make green?\na.Orange and blue b.Red and blue c.Blue and yellow d.Black and yellow",
             "The chief ore of Aluminium is?\na.Iron b.Cryolite c.Bauxite d.Haematite",
             "What is the capital of India?\na.Delhi b.Maharashtra c.Andra Pradesh d.Rajasthan",
             "What is 43+78?\na.120 b.121 c.122 d.131",
             "What is 2+2?\na.3 b.4 c.5 d.1",
             "What is the Italian word for PIE? \na.Mozarella b.Pasty c.Patty d.Pizza",
             "Water boils at 212 Units at which scale? \na.Fahrenheit b.Celsius c.Rankine d.Kelvin",
             "Which sea creature has three hearts? \na.Dolphin b.Octopus c.Walrus d.Seal",
             "Who was the character famous in our childhood rhymes associated with a lamb? \na.Mary b.Jack c.Johnny d.Mukesh",
             "How many bones does an adult human have? \na.206 b.208 c.201 d.196",
             "How many wonders are there in the world? \na.7 b.8 c.10 d.4",
             "What element does not exist? \na.Xf b.Re c.Si d.Pa",
             "How many states are there in India? \na.24 b.29 c.30 d.31",
             "Who invented the telephone? \na.A.G Bell b.John Wick c.Thomas Edison d.G Marconi",
             "Who is Loki? \na.God of Thunder b.God of Dwarves c.God of Mischief d.God of Gods",
             "Who was the first Indian female astronaut ? \na.Sunita Williams b.Kalpana Chawla c.None of them d.Both of them ",
             "What is the smallest continent? \na.Asia b.Antarctic c.Africa d.Australia",
             "The beaver is the national embelem of which country? \na.Zimbabwe b.Iceland c.Argentina d.Canada",
             "How many players are on the field in baseball? \na.6 b.7 c.9 d.8",
             "Hg stands for? \na.Mercury b.Hulgerium c.Argenine d.Halfnium",
             "Who gifted the Statue of Libery to the US? \na.Brazil b.France c.Wales d.Germany",
             "Which planet is closest to the sun? \na.Mercury b.Pluto c.Earth d.Venus",
             "Which state has the largest area? \na.Maharashtra b.Madhya Pradesh c.Uttar Pradesh d.Rajasthan.",
             "What was the world’s first high level programming language in 1957? \na.IBM FORTRAN b.CON c.Del d.Indic",
             "Nobel prize is awarded for which of the following disciplines: \na.Literature, peace and economics b.Medicine or Physiology c.Chemistry and Physics d.All the above",
             "Who is the Prime Minister of India? \na.Manmohan Singh b.Narendra Modi c.Ram Nath Kovind d.Hamid Ansari",
             "Who is the President of India? \na.Manmohan Singh b.Narendra Modi c.Ram Nath Kovind d.Hamid Ansari",
             "Total number of continents in the world: \na.6 b.7 c.9 d.8",
             "Taj Mahal was built by: \na.Akbar b.Humanyu c.Shah Jahan d.Aurangzeb"]

answers = ['d', 'c', 'c', 'a', 'b', 'b', 'd', 'a', 'b', 'a', 'a', 'a', 'a', 'b', 'a', 'c', 'b', 'd', 'd', 'c', 'a', 'b',
           'a', 'd', 'a', 'd', 'b', 'c', 'b', 'c']
